CREATE DATABASE IF NOT EXISTS utilities;

CREATE TABLE `owner` (
`id_owner` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(45) NOT NULL,
`surname` VARCHAR(30) NOT NULL,
`passport_series` VARCHAR(10) NOT NULL,
`passport_number` INT(6) UNSIGNED NOT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=utf8;